DEPTH = ../
SUBDIRS =

LINCFLAGS = $(RTKROOT)/geometry/_geometry.so $(RTKROOT)/samplers/_samplers.so $(RTKROOT)/misc/_misc.so $(RTKROOT)/restraints/_restraints.so $(RTKROOT)/builders/_builders.so

INCFLAGS += -I $(BGLROOT)

CSOURCES = SCenergyProvider biconn \

ISOURCES = scep
SWIGLIB = scep

-include $(DEPTH)/makedefs
# DO NOT DELETE
